FROM python:3.12.7

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install fastapi[standard] && pip install -r requirements.txt

COPY app .

CMD ["fastapi", "dev", "main.py", "--port", "8080", "--host", "0.0.0.0", "--reload"]
EXPOSE 8080