services:
  app:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
    ports:
     - "8080:8080"

  db:
    image: postgres:latest
    container_name: fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: fastapi_db
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - "1025:1025"  # SMTP port
      - "1080:1080"  # Web UI

volumes:
  postgres_data:
